version: '3'

services:
  vpn:
    build:
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    # does ports really do something for priviliged?
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    volumes:
      - ./.ikev2-vpn-data:/etc/ipsec.d